name: LoginMsg
version: ${project.version}
main: top.mccsdl.aclles.Aclles
api-version: 1.12
authors: [Aclles]
description: It's a collection of features That I need

commands:
  LoginMsg:
    description: Access to /LoginMsg command
    usage: /<command>
permissions:
  LoginMsg.*:
    description: Gives access to all doorman commands
    children:
      LoginMsg.reload: true
  LoginMsg.reload:
    description: <plugin name>.reload
    default: op
    permission-message: You don't have <permission>

