name: LoginMsg
version: 2.2
main: top.mccsdl.aclles.Aclles
api-version: 1.12
authors: [Aclles]
description: dome

#插件需要注册的命令
commands:
  #命令是LoginMsg
  LoginMsg:
    #描述
    description: "打开插件介绍"
    #用法
    usage: /LoginMsg
permissions:
  # 重载权限
  LoginMsg.reload:
    description: "此权限重启插件"
    default: op


